config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  resources :shops do
    resources :reviews, only: :create
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  monetize :amount_cents

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :shop
  validates :content, length: { minimum: 12 }
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user

  #adding reviews to model
  has_many :reviews, dependent: :destroy

  #adding mount_uploader for cloudinary
   mount_uploader :photo, PhotoUploader

   #money rails
    monetize :price_cents

    #adding geocoder config
    geocoded_by :address
    after_validation :geocode, if: :will_save_change_to_address?


    #adding rating
    accepts_nested_attributes_for :reviews

    #important when we play with money,pd: error no nos deja crear una shop
    validates :sku, presence: true, uniqueness: true

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 15 }
  validates :price, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    shop = Shop.find(params[:shop_id])
    order = Order.create!(shop_sku: shop.sku, amount: shop.price, state: 'pending', user: current_user)

    redirect_to new_order_payment_path(order)
    authorize order

  end

  def show
    @order = current_user.orders.where(state: 'paid').find(params[:id])
    authorize @order
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home

  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
      before_action :set_order
  def new

 authorize @order
  end

  def create
    authorize @order

    customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
  )

  charge = Stripe::Charge.create(
    customer:     customer.id,   # You should store this customer id and re-use it.
    amount:       @order.amount_cents,
    description:  "Payment for shop #{@order.shop_sku} for order #{@order.id}",
    currency:     @order.amount.currency
  )

  @order.update(payment: charge.to_json, state: 'paid')
  redirect_to order_path(@order)

rescue Stripe::CardError => e
  flash[:alert] = e.message
  redirect_to new_order_payment_path(@order)
 authorize @order
  end

  private

  def set_order
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
   # authorize @order
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_shop, only: [ :edit, :update, :destroy]


  def create
    @shop = Shop.find(params[:shop_id])
    @review = Review.new(review_params)
    @review.shop = @shop
    #ojo con la linea 9
    authorize @review.shop

    if @review.save
      respond_to do |format|
    format.html  {redirect_to shop_path(@shop)}
    format.js

  end

  else
  respond_to do  |format|
     format.html {render 'gyms/show'}
     format.js
  end

  end



  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)

  end

  def set_shop
  @shop = Shop.find(params[:id])
  authorize @shop



  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @shops = policy_scope(Shop).order(created_At: :desc)

  end

  def show
    @shop = Shop.find(params[:id])

  end

  def new
    @shop = Shop.new
    authorize @shop

  end

  def edit

  end

  def create
    @shop = Shop.new(shop_params)
    @shop.save
    @shop.user = current_user
    authorize @shop
    if @shop.save
      redirect_to @shop , notice: 'your shop was created thanks!'
    else
      render :edit
    end

  end

  def update

  end

  def destroy
    @shop.destroy
    redirect_to shop_index_path

  end

  private

  def shop_params
    params.require(:shop).permit(:name, :description, :price)

  end


end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index

    @shops = policy_scope(Shop).order(created_at: :desc)
    @shops = Shop.where.not(latitude: nil, longitude: nil)

    @markers = @shops.map do |shop|
      {
        lat: shop.latitude,
        lng: shop.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
        # Uncomment the above line if you want each of your markers to display a info window when clicked
        # (you will also need to create the partial "/flats/map_box")
      }
    end

  end

  def show
    @shop = Shop.find(params[:id])
    authorize @shop
    @review = Review.new

  end

  def new
    @shop = Shop.new
    authorize @shop

  end

  def edit

    @shop = Shop.find(params[:id])
    authorize @shop

  end

  def create
    @shop = Shop.new(shop_params)
    @shop.save
    @shop.user = current_user
    authorize @shop
    if @shop.save
      redirect_to @shop , notice: 'your shop was created thanks!'
    else
      render :edit
    end


  end

  def update
    @shop = Shop.find(params[:id])
    @shop.update(shop_params)
    if @shop.update(shop_params)
      redirect_to @shop, notice: "Your shop was updated, thanks"
    else
      render :edit
    end
    authorize @shop

  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    redirect_to shops_path
    #authorize @shop


  end

  private

  def set_shop
    @shop = Shop.find(params[:id])
    authorize @shop

  end

  def shop_params
    params.require(:shop).permit(:name, :description, :price, :photo, :sku, :address)

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Bungee+Shade" rel="stylesheet">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Bbshop</title>


    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>


    <%=stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->


  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
     <%#= javascript_include_tag "https://maps.googleapis.com/maps/api/js" %>
    <%= javascript_pack_tag 'application' %>
    <!-- adding script coming from google for their maps -->
     <!-- dont pay attention to line 27 -->
       <%#= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_SERVER_KEY']}" %>


  </body>
</html>

app/views/orders/show.html.erb
<h1>Order</h1>
<ul>
  <!-- is not working line 4 -->
<li> <%= @order.photo %></li>
  <li>Status: <%= @order.state %></li>
  <li>Item: <%= @order.shop_sku %></li>
  <li>Amount: <%= humanized_money_with_symbol(@order.amount) %></li>
<ul>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1503951914875-452162b0f3f1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80);">
  <div class="container">
    <h1>Bbshops Brings You <strong>An Easy way</strong> to <br><strong>Book your next Haircut Aroun the Globe!</strong>!</h1>
    <p>
      <!-- adding yarn packgae -->
      <span id="banner-typed-text"></span>

    </p>

     <%= link_to "Bshops", shops_path, class:"btn btn-success" %>
  </div>
</div>



    <div id="work">
      <h2>How It Works</h2>
    </div>



<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1496181832051-69dcf27fc27d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=889&q=80)">


    <div id="parraf">
      <div class="demo"></div>
    <a href="" id="demo">search</a>
    </div>

  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1512690459411-b9245aed614b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80)">
     <div id="find">
       <div class="demo"></div>
       <a href="" id="demo">Find</a>
     </div>


  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1549271568-e87e07c5406b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80)">
     <div id="book">
       <div class="demo"></div>
      <a href="" id="demo">Book</a>
     </div>


  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1519500528352-2d1460418d41?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80)">

    <div id="shine">
      <div class="demo"></div>
      <a href="" id="demo">Shine</a>
    </div>
   </div>

</div>

app/views/payments/new.html.erb
<h1>Purchase of shop<%= @order.shop_sku %></h1>
<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">

      <span>Amount: <%= humanized_money_with_symbol(@order.amount) %></span>
    </label>
  </article>


  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="My shop"
    data-email="<%= current_user.email %>"
    data-description="shop <%= @order.shop_sku %>"
    data-amount="<%= @order.amount_cents %>"
    data-currency="<%= @order.amount.currency %>"></script>

<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for([ shop, review ], remote: true) do |form| %>
  <%= form.input :content, as: :text %>
  <%= form.button :submit %>
<% end %>

app/views/reviews/_show.html.erb
<p> <%= review.content %></p>

app/views/reviews/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", shop: @shop, review: @review %>');
<% else %>
  addReview('<%= j render "reviews/show", review: @review %>');
  refreshForm('<%= j render "reviews/form", shop: @shop, review: Review.new %>');
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>

    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="https://juansport.herokuapp.com/"> Juan S.L</a>
    </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm  navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h3>BBSHOP</h3>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">


      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "New", new_shop_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Show", shops_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shops/_form.html.erb
<div class="container">
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
  <%= simple_form_for(shop) do |f| %>



  <!-- [...] -->
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <!-- [...] -->





  <div class="form-inputs">
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :price %>
  <%= f.input :sku %>



  <!-- remenber to ask about line 20 -->


</div>

<div class="form-actions">
  <% if policy(Shop).create? %>
  <%= f.button :submit %>

<% end %>

</div>

  <% end %>



  </div>

</div>


</div>

app/views/shops/destroy.js.erb
document.querySelector("[data-shop-id='<%= @shop.id %>']")
.remove();

app/views/shops/edit.html.erb
<h1>Edit your Bshops </h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %>
<%= link_to 'back', shops_path %>

app/views/shops/index.html.erb
<div class="container">

<div id="shops">
  <p>Bbshops</p>

</div>

<div class="cards">

  <% @shops.each do |shop| %>


 <div class="card"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path shop.photo, height: 330, width: 505, crop: :fill %>')">
  <div class="card-category"><%= link_to shop.name, shop_path(shop) %></div>
  <div class="card-description">
    <h2>Some stuff</h2>
    <p>Very cool stuff, useful and smart</p>
  </div>
  <a class="card-link" href="#" ></a>



 <% if policy(shop).create? %>
 <%= link_to "New Gym", new_shop_path %>
  <% end %>


<!-- removed polici of destroy method, 'cause I added it on the show view -->




</div>


<% end %>





 </div>




</div>





<!-- ADDING 2 container -->

<div class="container2">

  <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

</div>

app/views/shops/new.html.erb
<div class="newh1">

   <h1>Create your shop</h1>
</div>

<%= render 'form', shop: @shop %>

app/views/shops/show.html.erb
<div class="container">
  <div class="row justify-content-center">

     <div class="col-12 col-lg-6">



      <%= cl_image_tag @shop.photo, height: 300, width: 400, crop: :fill %>

      <h1>Name: <%= @shop.name %></h1>
      <h3>Description: <%= @shop.description %></h3>
      <h3>Address: <%= @shop.address %></h3>
      <p>Amount: <%= humanized_money_with_symbol(@shop.price) %></p>


       <!-- adding code to add form to create an order -->
          <%= form_tag orders_path do %>
         <%= hidden_field_tag 'shop_id', @shop.id %>
         <%= submit_tag 'Book', class: 'btn btn-primary' %>
       <% end %>




      <!-- adding code for reviews -->
      <h2>
        <%= pluralize @shop.reviews.size,  "Review" %>

      </h2>

      <div id="reviews">
            <% if @shop.reviews.blank? %>
        Be the first to leave a review for <%= @shop.name %>
      <% else %>
        <% @shop.reviews.each do |review| %>
          <%= render 'reviews/show', review: review %>
        <% end %>
      <% end %>



      </div>





      <%= render 'reviews/form', shop: @shop, review: @review %>

      <!-- adding rating  system-->
      <%= simple_form_for(@shop, html: { class: "review_form" }) do |f| %>

      <%= simple_form_for @shop do |f| %>
      <%= f.simple_fields_for :review do |r| %>
      <%= r.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
       <% end %>
         <%#= f.submit, class: "hidden" %>

      <%= f.button :submit, class: "hidden" %>
     <% end %>
<% end %>



                  <ul>


                    <% if policy(@shop).create? %>
                <%= link_to "New Gym", new_shop_path %>
                <% end %>
             </ul>


             <ul>
             <% if policy(@shop).destroy? %>

             <li data-shop-id="<%= @shop.id %>">
            <%= link_to "Delete Bshop", @shop, method: :delete, remote: true, data:{ confirm: "Are u sure buddy?"} %>
          </li>
        <% end %>

            <% if policy(@shop).edit? %>
            <li data-shop-id= "<%= @shop.id %>">
            <%= link_to "Update", edit_shop_path(@shop)  %>

            </li>
            <% end %>


    </ul>





     </div>

  </div>

</div>